version: 2.1
jobs:
  build_wheels:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - run:
          command: |
           python3 -m pip install --upgrade build
           make build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
            - build

  test_pypi_publish:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout  # checkout source code to working directory
      - attach_workspace:
          at: ~/project/
      - run:
          name: init .pypirc
          command: |
            echo -e "[testpypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPY_TEST_TOKEN" >> ~/.pypirc
      - run:
          name: deploy to pypi-test
          command: |  # create whl, install twine and publish to Test PyPI
            python3 -m pip install --upgrade build
            make build
            pip3 install twine
            twine upload --repository testpypi dist/*

  pypi_publish:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout  # checkout source code to working directory
      - attach_workspace:
          at: ~/project/
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = __token__" >> ~/.pypirc
            echo -e "password = $PYPY_TOKEN" >> ~/.pypirc
            python3 version.py
      - run:
          command: |  # create whl, install twine and publish to PyPI
            python3 -m pip install --upgrade build twine
            make build
            pip3 install twine
            twine upload dist/*
          environment:
            TWINE_USER: "__token__"
            TWINE_PASSWORD: $PYPY_TOKEN
workflows:
  build_test_publish:
    jobs:
      - build_wheels
      - test_pypi_publish:
          requires:
            - build_wheels
          filters:
            branches:
              only:
                - testpypi
      - pypi_publish:
          requires:
            - build_wheels
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
